{"name": "Two same couriers registration error check", "status": "passed", "description": "Second request to create a courier, verify expected error and delete new courier", "start": 1716760170710, "stop": 1716760171013, "uuid": "a04bd10d-df39-4011-9c05-b7adcb0deb1f", "historyId": "c4b90225c397569355a55129c1a8cc73", "testCaseId": "c4b90225c397569355a55129c1a8cc73", "fullName": "tests.test_create_courier.TestCourierCreate#test_double_registration_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCourierCreate"}, {"name": "host", "value": "PC"}, {"name": "thread", "value": "352-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}